version: '2'
services:
  web:
    build: .
    volumes:
     - web_data:/app/www:rw
    environment:
     - NODE_ENV=development
     - API_URL=http://api.example.localhost
     - DEBUG=true
    privileged: true
  http:
    restart: always
    build: ./http
    labels:
     - "traefik.enable=true"
     - "traefik.backend=example.localhost"
     - "traefik.frontend.rule=Host:example.localhost"
    volumes:
     - web_data:/app/www
    expose:
     - 80
     - 443
    ports:
     - 80
     - 443
    tty: true
    networks:
     - frontend
     - backend
    privileged: true
volumes:
  web_data: {}
networks:
  frontend:
        external: true
        # driver: bridge
        # driver_opts:
        #   com.docker.network.enable_ipv6: "true"
  backend:
        external: true
        # driver: bridge
        # driver_opts:
        #   com.docker.network.enable_ipv6: "true"
