version: '2'
services:
  web:
    build: .
    volumes:
     - web_data:/app/www:rw
    environment:
     - NODE_ENV=development
     - API_URL=http://localhost:8888
     - DEBUG=true
    privileged: true
  http:
    restart: always
    build: ./http
    volumes:
     - web_data:/app/www
    ports:
     - "80:80"
     - "443:443"
    tty: true
    privileged: true
volumes:
  web_data: {}
